### PR TITLE
add option to fetch groups from graph api instead of dn param in access_token

### PR DESCRIPTION
**Pull request by Garlov**

### CODE REVIEW

**Comment by Garlov** [comment]
@GlennRicaud Time to review and possibly merge this soon?

**Comment by GlennRicaud** [comment]
Sorry for the delay. We looked at it and liked it (clever workaround)

The only problem here is that the name is based on adGroup.displayName which might change I guess.
Name of principals (user, groups and roles) should never change (Because of how principals are referenced). It would be better to use adGroup.id for example.

**Comment by sigdestad** [comment]
Also, you need to stick to the auth lib for compatibility, as we May change stuff behind the scenes

**Comment by Garlov** [comment]
I've updated the azure ad login to 7.0 semantics, and I've amended the problems you had.

I've also added a config option to force https on redirect and return urls.

**Pull request merged**
